#!/usr/bin/env python3
"""Generate the 30 devops agent profiles (agents/devops-NN.json) and the
30 skill runbooks (skills/<specialty>.md) from one data table.
Run: python3 train/generate.py
Dataset mapping verified 2026-09-17 against datasets-server.huggingface.co.
Substitutions (unusable -> replacement):
  bigcode/the-stack-smol (401)            -> sahil2801/CodeAlpaca-20k
  codeparrot/github-code-clean (/rows job killed) -> theblackcat102/evol-codealpaca-v1
  jtatman/python-code-instructions-18k-alpaca (401) -> theblackcat102/evol-codealpaca-v1
  Salesforce/xlam-function-calling-60k (401)       -> glaiveai/glaive-code-assistant-v3
  nvidia/OpenCodeInstruct (/rows config mismatch)  -> ise-uiuc/Magicoder-OSS-Instruct-75K
  neulab/conala (/rows 404)               -> sahil2801/CodeAlpaca-20k
  openai_humaneval (404)                  -> google-research-datasets/mbpp
"""
import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS = os.path.join(BASE, "agents")
SKILLS = os.path.join(BASE, "skills")

def ds(ds_id, config="default", split="train"):
    return {"id": ds_id, "config": config, "split": split}

SPECS = [
 dict(key="docker", name="Docker Specialist",
      skills=["docker build", "docker compose", "multi-stage builds", "image layer caching",
              "registry push/pull", "docker networking", "volume management"],
      datasets=[ds("sahil2801/CodeAlpaca-20k"), ds("glaiveai/glaive-code-assistant-v3")],
      description="Builds, optimizes and operates Docker images and Compose stacks.",
      when="Use for anything container-image related: Dockerfiles, Compose files, registries, image size/perf.",
      commands=["docker build -t app:1.0 .", "docker compose up -d --build",
                "docker images --format '{{.Repository}}:{{.Tag}} {{.Size}}'",
                "docker system prune -af --volumes", "docker inspect <c> | jq .",
                "docker logs -f --tail 100 <c>", "docker exec -it <c> sh"],
      gotchas=["Never bake secrets into layers; use --secret or runtime env.",
               "Pin base image digests in production Dockerfiles.",
               "`latest` tag + cached layers = stale deploys; use immutable tags."]),
 dict(key="kubernetes", name="Kubernetes Operator",
      skills=["kubectl", "deployments/statefulsets", "services/ingress", "RBAC",
              "helm values", "resource limits", "pod debugging", "namespaces"],
      datasets=[ds("theblackcat102/evol-codealpaca-v1"), ds("teknium/OpenHermes-2.5")],
      description="Deploys and debugs workloads on Kubernetes clusters.",
      when="Use for manifests, kubectl triage, scheduling, RBAC, upgrades.",
      commands=["kubectl get pods -A -o wide", "kubectl describe pod <p>",
                "kubectl logs -f deploy/<d> --previous", "kubectl rollout status deploy/<d>",
                "kubectl apply -f manifests/", "kubectl top pods -A",
                "kubectl auth can-i --list --as=system:serviceaccount:ns:sa"],
      gotchas=["Always set requests/limits; no limits = noisy-neighbor evictions.",
               "CrashLoopBackOff: check `logs --previous` before redeploying.",
               "Apply is declarative; avoid imperative edits on live objects."]),
 dict(key="helm", name="Helm Chart Engineer",
      skills=["helm install/upgrade", "chart templating", "values.yaml", "chart hooks",
              "helmfile", "chart testing"],
      datasets=[ds("sahil2801/CodeAlpaca-20k"), ds("yahma/alpaca-cleaned")],
      description="Packages and releases applications as Helm charts.",
      when="Use for chart authoring, templating bugs, releases and rollbacks.",
      commands=["helm template ./chart --values vals.yaml | less",
                "helm upgrade --install app ./chart -n prod --atomic --timeout 10m",
                "helm lint ./chart", "helm rollback app 2",
                "helm get values app -n prod", "helm unittest ./chart"],
      gotchas=["`--atomic` auto-rolls back failed upgrades; use it in CI.",
               "Quote template values that may parse as YAML types.",
               "Never store secrets in values.yaml; use external-secrets."]),
 dict(key="terraform", name="Terraform IaC Engineer",
      skills=["terraform plan/apply", "HCL modules", "state management", "workspaces",
              "terraform import", "provider config"],
      datasets=[ds("ise-uiuc/Magicoder-OSS-Instruct-75K"), ds("databricks/databricks-dolly-15k")],
      description="Provisions cloud infrastructure with Terraform/OpenTofu.",
      when="Use for HCL modules, plan review, state surgery, drift.",
      commands=["terraform init -upgrade", "terraform plan -out=tfplan",
                "terraform apply tfplan", "terraform state list | head",
                "terraform import aws_instance.web i-123", "tofu fmt -recursive"],
      gotchas=["Remote state + locking (S3+DynamoDB / GCS) is mandatory for teams.",
               "Review the plan, not just the code; `apply` on red plans is how outages happen.",
               "Tainted resources get replaced next apply; untaint if it was a fluke."]),
 dict(key="ansible", name="Ansible Automation Engineer",
      skills=["playbooks", "roles", "inventory", "jinja2 templating", "vault",
              "handlers", "idempotency"],
      datasets=[ds("theblackcat102/evol-codealpaca-v1"), ds("tatsu-lab/alpaca")],
      description="Automates config management with Ansible playbooks and roles.",
      when="Use for playbooks, inventory, idempotent config enforcement.",
      commands=["ansible-playbook -i inv site.yml --check --diff",
                "ansible all -i inv -m ping", "ansible-vault encrypt secrets.yml",
                "ansible-galaxy install -r requirements.yml",
                "ansible-playbook site.yml --limit web --tags nginx"],
      gotchas=["Design tasks idempotent; reruns must be no-ops.",
               "`--check --diff` first on anything touching production.",
               "Vault-encrypt secret files; never commit plaintext."]),
 dict(key="pulumi", name="Pulumi IaC Developer",
      skills=["pulumi up/preview", "stacks", "typescript/python SDKs", "policy packs",
              "stack references"],
      datasets=[ds("ise-uiuc/Magicoder-OSS-Instruct-75K"), ds("mlabonne/FineTome-100k")],
      description="Manages infrastructure as real code with Pulumi.",
      when="Use for Pulumi programs, stacks, previews and policy.",
      commands=["pulumi preview --diff", "pulumi up --yes",
                "pulumi stack init prod", "pulumi config set --secret dbPass x",
                "pulumi destroy --yes", "pulumi stack rm dev"],
      gotchas=["Use `--secret` for config; plaintext config leaks in state.",
               "Passphrase or KMS backend for stack secrets is required.",
               "Preview diffs before every `up`; code review the diff."]),
 dict(key="github-actions", name="GitHub Actions Engineer",
      skills=["workflow YAML", "actions/cache", "matrix builds", "OIDC", "reusable workflows",
              "self-hosted runners"],
      datasets=[ds("sahil2801/CodeAlpaca-20k"), ds("m-a-p/CodeFeedback-Filtered-Instruction")],
      description="Builds CI/CD pipelines with GitHub Actions.",
      when="Use for workflow authoring, caching, releases, runner issues.",
      commands=["gh workflow run ci.yml -f ref=main", "gh run list --limit 5",
                "gh run view <id> --log-failed", "act -j build  # local test",
                "gh secret set TOKEN --body x"],
      gotchas=["Pin third-party actions to SHAs, not moving tags.",
               "Use OIDC instead of long-lived PATs wherever possible.",
               "`pull_request_target` runs in base context; never checkout untrusted code with it."]),
 dict(key="gitlab-ci", name="GitLab CI Engineer",
      skills=[".gitlab-ci.yml", "pipeline stages", "artifacts/cache", "environments",
              "rules/workflows", "runners"],
      datasets=[ds("theblackcat102/evol-codealpaca-v1"), ds("glaiveai/glaive-code-assistant-v3")],
      description="Builds CI/CD pipelines with GitLab CI.",
      when="Use for pipeline YAML, runners, environments, releases.",
      commands=["glab pipeline list", "glab ci lint", "glab pipeline view <id>",
                "gitlab-runner verify", "glab variable set KEY val --masked"],
      gotchas=["`rules:` replaced `only/except`; mixing both is a classic bug.",
               "Mask and protect variables holding secrets.",
               "Cache vs artifacts: cache is best-effort, artifacts are guaranteed."]),
 dict(key="jenkins", name="Jenkins Pipeline Engineer",
      skills=["Jenkinsfile", "declarative pipeline", "shared libraries", "agents",
              "credentials binding", "Blue Ocean"],
      datasets=[ds("ise-uiuc/Magicoder-OSS-Instruct-75K"), ds("databricks/databricks-dolly-15k")],
      description="Maintains Jenkins controllers, agents and pipelines.",
      when="Use for Jenkinsfiles, agent pools, plugin and credential issues.",
      commands=["java -jar jenkins-cli.jar -s $URL build job -s",
                "jenkins-cli list-jobs", "groovy console: println Jenkins.instance.pluginManager.plugins"],
      gotchas=["Keep Jenkins + plugins patched; unpatched Jenkins gets owned.",
               "Use credentials binding; never echo secrets in sh steps.",
               "Declarative pipelines beat scripted for maintainability."]),
 dict(key="argocd", name="Argo CD GitOps Operator",
      skills=["argocd app", "gitops", "sync waves", "app of apps", "image updater",
              "repo server"],
      datasets=[ds("sahil2801/CodeAlpaca-20k"), ds("teknium/OpenHermes-2.5")],
      description="Runs GitOps continuous delivery with Argo CD.",
      when="Use for Application manifests, sync failures, drift, promotions.",
      commands=["argocd app list", "argocd app sync myapp --prune",
                "argocd app diff myapp", "argocd app get myapp --show-operation",
                "argocd admin settings rbac can megan get applications"],
      gotchas=["OutOfSync is normal; investigate only Unknown/Degraded.",
               "Use sync waves + hooks to order DB migrations before app rollout.",
               "Auto-sync + prune in prod needs branch protection discipline."]),
 dict(key="prometheus", name="Prometheus Monitoring Engineer",
      skills=["PromQL", "alertmanager", "recording rules", "exporters", "service discovery",
              "remote write"],
      datasets=[ds("yahma/alpaca-cleaned"), ds("HuggingFaceH4/no_robots")],
      description="Instruments and alerts with Prometheus + Alertmanager.",
      when="Use for PromQL queries, alert rules, exporter gaps, cardinality.",
      commands=["rate(http_requests_total[5m])",
                "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
                "promtool check rules rules.yml", "amtool config routes test --config.file=am.yml"],
      gotchas=["High cardinality labels (user IDs) will OOM your Prometheus.",
               "`rate()` needs range >= 4x scrape interval to be stable.",
               "Alert on symptoms (latency/errors), not causes (CPU)."]),
 dict(key="grafana", name="Grafana Dashboard Engineer",
      skills=["dashboards", "panels", "variables", "alerting", "loki/tempo integration",
              "provisioning"],
      datasets=[ds("yahma/alpaca-cleaned"), ds("databricks/databricks-dolly-15k")],
      description="Builds dashboards and visualization in Grafana.",
      when="Use for dashboards, variables, alert rules, datasource config.",
      commands=["grafana-cli admin reset-admin-password x",
                "provisioning: dashboards/datasources YAML under /etc/grafana/provisioning"],
      gotchas=["Template dashboards with variables; one dashboard per service, not per host.",
               "Provision dashboards as code so they survive upgrades.",
               "Alerting: prefer Grafana managed alerts over panel alerts."]),
 dict(key="elk-logging", name="ELK Logging Engineer",
      skills=["elasticsearch", "logstash/filebeat", "kibana", "index lifecycle",
              "mappings", "log parsing"],
      datasets=[ds("tatsu-lab/alpaca"), ds("mlabonne/FineTome-100k")],
      description="Centralizes and queries logs with the Elastic stack.",
      when="Use for index design, pipeline parsing, Kibana queries, retention.",
      commands=["GET /logs-*/_search", "PUT /_ilm/policy/logs-30d",
                "filebeat test config", "logstash -t -f pipeline.conf"],
      gotchas=["Set explicit mappings; dynamic mapping explosions kill clusters.",
               "ILM rollover keeps shard counts sane; don't hand-roll retention.",
               "Parse at the edge (Filebeat) to keep Logstash simple."]),
 dict(key="linux-admin", name="Linux Systems Administrator",
      skills=["systemd", "users/groups", "filesystem", "package mgmt", "cron",
              "sysctl tuning", "troubleshooting"],
      datasets=[ds("m-a-p/CodeFeedback-Filtered-Instruction"), ds("tatsu-lab/alpaca")],
      description="Administers Linux servers: services, users, storage, tuning.",
      when="Use for systemd units, permissions, disk, package and boot issues.",
      commands=["systemctl status x --no-pager", "journalctl -u x -f",
                "df -h; du -sh /* 2>/dev/null | sort -h | tail",
                "ss -tlnp", "sysctl -w vm.swappiness=10"],
      gotchas=["Check `journalctl`, not just the service status.",
               "Full disks cause the weirdest failures; monitor inodes too.",
               "Use `systemctl edit` drop-ins instead of editing unit files."]),
 dict(key="bash-scripting", name="Bash Scripting Specialist",
      skills=["bash", "shell pipelines", "awk/sed", "error handling", "cron jobs",
              "portable scripting"],
      datasets=[ds("sahil2801/CodeAlpaca-20k"), ds("theblackcat102/evol-codealpaca-v1")],
      description="Writes robust shell scripts and one-liners.",
      when="Use for scripts, cron jobs, text processing, glue automation.",
      commands=["set -euo pipefail", "awk '{print $1}' file | sort | uniq -c | sort -nr",
                "find . -name '*.log' -mtime +7 -delete", "parallel -j8 cmd ::: args"],
      gotchas=["Always start scripts with `set -euo pipefail`.",
               "Quote every variable: \"$var\", never $var.",
               "Shellcheck your scripts; it catches 90% of bugs."]),
 dict(key="python-automation", name="Python Automation Developer",
      skills=["python scripting", "requests", "boto3", "subprocess", "argparse",
              "virtualenvs", "packaging"],
      datasets=[ds("google-research-datasets/mbpp", "full"), ds("theblackcat102/evol-codealpaca-v1")],
      description="Automates ops tasks with Python.",
      when="Use for Python tooling, API clients, data munging, SDK work.",
      commands=["python3 -m venv .venv && . .venv/bin/activate",
                "pip install --user --break-system-packages pkg",
                "python3 -m py_compile script.py", "ruff check ."],
      gotchas=["Pin dependencies; unpinned pip installs rot.",
               "Never `shell=True` with untrusted input.",
               "Log structured output; print-debugging doesn't scale."]),
 dict(key="networking", name="Network Engineer",
      skills=["TCP/IP", "DNS", "TLS", "load balancing", "firewalls", "VPN",
              "packet capture"],
      datasets=[ds("tatsu-lab/alpaca"), ds("teknium/OpenHermes-2.5")],
      description="Diagnoses network paths, DNS, TLS and connectivity.",
      when="Use for connectivity, DNS, cert, latency and firewall issues.",
      commands=["dig +short example.com", "mtr -rwc 20 host",
                "openssl s_client -connect host:443 -servername host | openssl x509 -noout -dates",
                "tcpdump -i any port 443 -c 50 -w cap.pcap", "ss -tlnp | head"],
      gotchas=["It's always DNS. Check DNS first, seriously.",
               "MTU/fragmentation causes 'works locally, fails remotely'.",
               "Capture with tcpdump before guessing; guessers lose hours."]),
 dict(key="nginx", name="Nginx Reverse-Proxy Engineer",
      skills=["nginx config", "reverse proxy", "TLS termination", "rate limiting",
              "caching", "load balancing"],
      datasets=[ds("yahma/alpaca-cleaned"), ds("sahil2801/CodeAlpaca-20k")],
      description="Configures Nginx as proxy, LB and static server.",
      when="Use for vhosts, proxying, TLS, rewrites, rate limits.",
      commands=["nginx -t && systemctl reload nginx",
                "proxy_pass http://upstream;", "nginx -T | less  # dump effective config"],
      gotchas=["`nginx -t` before every reload; a bad config drops traffic.",
               "Trailing slash in proxy_pass changes URI mapping semantics.",
               "Set client_max_body_size or uploads fail at 1MB default."]),
 dict(key="postgres", name="PostgreSQL DBA",
      skills=["psql", "backups/pitr", "replication", "indexing", "vacuum",
              "query tuning", "pg_hba"],
      datasets=[ds("ise-uiuc/Magicoder-OSS-Instruct-75K"), ds("databricks/databricks-dolly-15k")],
      description="Operates PostgreSQL: backups, replication, tuning.",
      when="Use for slow queries, replication lag, backups, upgrades.",
      commands=["EXPLAIN (ANALYZE, BUFFERS) SELECT ...;",
                "pg_basebackup -D /backup -Ft -z -P",
                "SELECT * FROM pg_stat_replication;",
                "VACUUM (ANALYZE, VERBOSE) t;", "pg_dump -Fc db > db.dump"],
      gotchas=["Test restores, not just backups; untested backups are wishes.",
               "Missing indexes show up in pg_stat_user_tables seq_scan counts.",
               "Never run DDL without checking for lock queues on busy tables."]),
 dict(key="redis", name="Redis Operator",
      skills=["redis-cli", "persistence RDB/AOF", "replication/sentinel", "cluster",
              "eviction policies", "key design"],
      datasets=[ds("tatsu-lab/alpaca"), ds("glaiveai/glaive-code-assistant-v3")],
      description="Operates Redis caches, queues and stores.",
      when="Use for memory, persistence, replication, latency issues.",
      commands=["redis-cli INFO memory", "redis-cli --latency-history",
                "redis-cli --rdb dump.rdb", "CONFIG GET maxmemory*",
                "redis-cli --bigkeys"],
      gotchas=["Set maxmemory + eviction policy; OOM kills the process.",
               "KEYS * blocks; use SCAN in production.",
               "AOF everysec is the sane durability default."]),
 dict(key="kafka", name="Kafka Streaming Engineer",
      skills=["topics/partitions", "consumer groups", "brokers", "schema registry",
              "kSQL", "lag monitoring"],
      datasets=[ds("mlabonne/FineTome-100k"), ds("HuggingFaceH4/ultrachat_200k", "default", "train_sft")],
      description="Runs Kafka clusters, topics and consumers.",
      when="Use for lag, rebalancing, partition design, broker ops.",
      commands=["kafka-topics --describe --topic t --bootstrap-server b:9092",
                "kafka-consumer-groups --describe --group g --bootstrap-server b:9092",
                "kafka-reassign-partitions ..."],
      gotchas=["More partitions != always better; rebalances get expensive.",
               "Monitor consumer lag; it's the one metric that matters.",
               "Set replication factor 3 and min ISR 2 for anything real."]),
 dict(key="vault-secrets", name="Vault Secrets Engineer",
      skills=["hashicorp vault", "dynamic secrets", "PKI", "transit encryption",
              "policies", "unseal/raft"],
      datasets=[ds("HuggingFaceH4/no_robots"), ds("teknium/OpenHermes-2.5")],
      description="Manages secrets with HashiCorp Vault.",
      when="Use for Vault policies, auth methods, dynamic creds, rotation.",
      commands=["vault kv put secret/app key=val", "vault policy write app policy.hcl",
                "vault auth enable approle", "vault operator unseal",
                "vault token create -policy=app -ttl=1h"],
      gotchas=["Root token is break-glass only; revoke it after init.",
               "Short TTLs + renewal beat long-lived tokens.",
               "Back up Raft snapshots; losing Vault = losing everything."]),
 dict(key="aws", name="AWS Cloud Engineer",
      skills=["EC2/VPC", "IAM", "S3", "RDS", "ELB", "CloudWatch", "aws cli"],
      datasets=[ds("teknium/OpenHermes-2.5"), ds("databricks/databricks-dolly-15k")],
      description="Builds and operates workloads on AWS.",
      when="Use for EC2/VPC/IAM/S3/RDS, CLI work, cost triage.",
      commands=["aws ec2 describe-instances --query ...",
                "aws s3 sync ./dist s3://bucket --delete",
                "aws iam get-account-authorization-details | less"],
      gotchas=["Least-privilege IAM; no `*` actions in production policies.",
               "S3 buckets: block public access by default, always.",
               "Tag everything; untagged spend is unmanageable spend."]),
 dict(key="gcp", name="GCP Cloud Engineer",
      skills=["GCE/GKE", "IAM", "Cloud Storage", "Cloud SQL", "VPC", "gcloud cli",
              "billing budgets"],
      datasets=[ds("teknium/OpenHermes-2.5"), ds("yahma/alpaca-cleaned")],
      description="Builds and operates workloads on Google Cloud.",
      when="Use for GCE/GKE/IAM/Storage, gcloud work, budget guardrails.",
      commands=["gcloud compute instances list",
                "gsutil rsync -r ./dist gs://bucket",
                "gcloud iam service-accounts list"],
      gotchas=["Budgets are alerts, not hard caps; pair with quotas.",
               "Service accounts: one per workload, minimal roles.",
               "Enable audit logs before you need them."]),
 dict(key="azure", name="Azure Cloud Engineer",
      skills=["VMs/VNet", "Entra ID", "Blob Storage", "AKS", "az cli", "ARM/Bicep"],
      datasets=[ds("teknium/OpenHermes-2.5"), ds("tatsu-lab/alpaca")],
      description="Builds and operates workloads on Azure.",
      when="Use for VMs/VNet/AKS/Entra, az CLI, Bicep templates.",
      commands=["az vm list -o table", "az storage blob upload-batch ...",
                "az aks get-credentials -g rg -n cluster"],
      gotchas=["Resource groups are blast-radius boundaries; plan them.",
               "Managed identities beat stored credentials every time.",
               "Bicep over raw ARM JSON for sanity."]),
 dict(key="security-hardening", name="Security Hardening Engineer",
      skills=["CIS benchmarks", "SSH hardening", "firewall rules", "patching",
              "container scanning", "least privilege"],
      datasets=[ds("mlabonne/FineTome-100k"), ds("HuggingFaceH4/no_robots")],
      description="Hardens systems, images and configs against attack.",
      when="Use for CIS baselines, SSH/TLS config, image scanning, audits.",
      commands=["lynis audit system", "trivy image app:1.0",
                "sshd -T | grep -i permit", "ufw status verbose"],
      gotchas=["Disable password auth on SSH; keys only.",
               "Scan images in CI; fail builds on critical CVEs.",
               "Hardening without patching is theater; patch first."]),
 dict(key="incident-response", name="Incident Response Engineer",
      skills=["triage", "postmortems", "runbooks", "on-call", "debugging",
              "blameless review"],
      datasets=[ds("SWE-Gym/SWE-Gym"), ds("m-a-p/CodeFeedback-Filtered-Instruction")],
      description="Leads incident triage, mitigation and postmortems.",
      when="Use for outages, Sev triage, comms, postmortem writeups.",
      commands=["kubectl get events -A --sort-by=.lastTimestamp | tail -20",
                "journalctl --since '30 min ago' -p err",
                "git log --oneline -20  # what changed recently?"],
      gotchas=["Mitigate first, root-cause later; MTTR beats perfect diagnosis.",
               "What changed? Deploys/config changes cause most incidents.",
               "Write the postmortem within 48h or the lessons evaporate."]),
 dict(key="backup-dr", name="Backup & DR Engineer",
      skills=["backup strategies", "RPO/RTO", "restore testing", "snapshots",
              "offsite copies", "disaster recovery plans"],
      datasets=[ds("databricks/databricks-dolly-15k"), ds("HuggingFaceH4/no_robots")],
      description="Designs backups and disaster recovery that actually restore.",
      when="Use for backup design, RPO/RTO, restore drills, replication.",
      commands=["restic snapshots", "restic check", "pg_basebackup ...",
                "velero backup create daily --include-namespaces prod"],
      gotchas=["A backup you never restored is not a backup.",
               "3-2-1 rule: 3 copies, 2 media, 1 offsite.",
               "Document the restore runbook; panic is not a procedure."]),
 dict(key="load-testing", name="Load Testing Engineer",
      skills=["k6", "locust", "JMeter", "capacity planning", "bottleneck analysis",
              "SLOs"],
      datasets=[ds("theblackcat102/evol-codealpaca-v1"), ds("sahil2801/CodeAlpaca-20k")],
      description="Proves systems hold up under load with k6/Locust/JMeter.",
      when="Use for load scripts, capacity questions, perf regressions.",
      commands=["k6 run --vus 100 --duration 5m script.js",
                "locust -f locustfile.py --headless -u 200 -r 20",
                "ab -n 10000 -c 100 https://app/health"],
      gotchas=["Test from outside your VPC; localhost lies.",
               "Ramp gradually; instant 10k VUs tests your LB, not your app.",
               "Watch p95/p99, not averages; averages hide pain."]),
 dict(key="service-mesh", name="Service Mesh Engineer",
      skills=["istio", "linkerd", "mTLS", "traffic shifting", "observability",
              "ingress gateways"],
      datasets=[ds("glaiveai/glaive-code-assistant-v3"), ds("teknium/OpenHermes-2.5")],
      description="Runs Istio/Linkerd meshes: mTLS, routing, resilience.",
      when="Use for sidecars, mTLS, canary routing, mesh upgrades.",
      commands=["istioctl analyze -A", "kubectl get vs -A",
                "linkerd check", "istioctl proxy-config cluster deploy/x"],
      gotchas=["mTLS STRICT mode breaks anything without a sidecar; migrate carefully.",
               "Mesh upgrades: control plane first, then data plane.",
               "Start with Linkerd if Istio's complexity isn't justified."]),
]

def main():
    os.makedirs(AGENTS, exist_ok=True)
    os.makedirs(SKILLS, exist_ok=True)
    for i, s in enumerate(SPECS, 1):
        aid = f"devops-{i:02d}"
        profile = {
            "id": aid,
            "name": s["name"],
            "specialty": s["key"],
            "skills": s["skills"],
            "hf_datasets": s["datasets"],
            "description": s["description"],
        }
        with open(os.path.join(AGENTS, f"{aid}.json"), "w") as f:
            json.dump(profile, f, indent=2)
        lines = [f"# {s['name']} runbook", "",
                 f"Agent: `{aid}` — {s['description']}", "",
                 "## When to use", s["when"], "",
                 "## Key commands"]
        lines += [f"- `{c}`" for c in s["commands"]]
        lines += ["", "## Gotchas"]
        lines += [f"- {g}" for g in s["gotchas"]]
        text = "\n".join(lines) + "\n"
        assert len(text.splitlines()) <= 40, aid
        with open(os.path.join(SKILLS, f"{s['key']}.md"), "w") as f:
            f.write(text)
    print(f"wrote {len(SPECS)} agent profiles -> {AGENTS}")
    print(f"wrote {len(SPECS)} runbooks -> {SKILLS}")

if __name__ == "__main__":
    main()
